services:
  spark-iceberg:
    image: spark-iceberg
    container_name: spark-iceberg
    build: ./spark
    #entrypoint: ["./entrypoint.sh", "master"]
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "8888:8888"
      - "8080:8080"

  #  spark-worker:
  #    container_name: spark-worker
  #    image: spark-iceberg
  #    #entrypoint: ["./entrypoint.sh", "worker"]
  #    depends_on:
  #      - spark-iceberg
  #    volumes:
  #      - ./data:/opt/spark/data
  #      - ./spark_apps:/opt/spark/apps
  #      - ./spark-logs:/opt/spark/spark-events
  #
  #    ports:
  #      - "8081:8081"
