services:
  spark-iceberg:
    image: spark-iceberg
    container_name: spark-iceberg
    # build: ./spark
    build:
      context: ./spark
      args:
        SPARK_DEFAULTS_CONF: spark-defaults-pg-catalog.conf
    #entrypoint: ["./entrypoint.sh", "master"]
    volumes:
      - ./warehouse:/home/iceberg/warehouse
      - ./notebooks:/home/iceberg/notebooks
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - ./spark-logs:/opt/spark/spark-events
    ports:
      - "8888:8888"
      - "8080:8080"

  pg-catalog:
    image: postgres:latest
    container_name: pg_catalog
    environment:
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: iceberg
      POSTGRES_DB: iceberg
    ports:
      - "5432:5432"

  #  spark-worker:
  #    container_name: spark-worker
  #    image: spark-iceberg
  #    #entrypoint: ["./entrypoint.sh", "worker"]
  #    depends_on:
  #      - spark-iceberg
  #    volumes:
  #      - ./data:/opt/spark/data
  #      - ./spark_apps:/opt/spark/apps
  #      - ./spark-logs:/opt/spark/spark-events
  #
  #    ports:
  #      - "8081:8081"
