services:
  minio-iceberg:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    volumes:
      - ./warehouse:/data
    ports:
      - "9001:9001"
      - "9000:9000" # this ia api port
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "mc alias set minio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && mc mb minio/warehouse && mc anonymous set public minio/warehouse"]
      interval: 2s
      timeout: 2s
      retries: 5

  pg-catalog:
    image: postgres:latest
    environment:
      POSTGRES_USER: iceberg
      POSTGRES_PASSWORD: iceberg
      POSTGRES_DB: iceberg
    ports:
      - "5432:5432"
    volumes:
      - ./iceberg-setup.sql:/docker-entrypoint-initdb.d/iceberg-setup.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iceberg -d iceberg"]
      interval: 5s
      timeout: 5s
      retries: 5

  trino:
    image: trinodb/trino:latest
    hostname: trino
    ports:
      - "8080:8080"
    volumes:
      - ./trino/catalog:/etc/trino/catalog
      #- ./trino/config.properties:/etc/trino/config.properties
    depends_on:
      pg-catalog:
        condition: service_healthy